INSERT INTO `materias` (`idMateria`, `nombreMateria`, `semestre`, `categorias`) VALUES
(1, 'Algoritmia', 1, 'Programacion e Informatica'),
(2, 'Desarrollo Organizacional', 1, 'Entorno Social'),
(3, 'Arquitectura de Computadoras', 1, 'Arquitectura de Computadoras'),
(4, 'Matemáticas Discretas', 1, 'Matematicas'),
(5, 'Desarrollo de Habilidades Cogn', 1, 'Entorno Social'),
(6, 'Algebra', 1, 'ITSE'),
(7, 'Algoritmos y Programacion Estr', 1, 'ITSE'),
(8, 'Calculo Diferencial e Integral', 1, 'ITSE'),
(9, 'Comunicacion Oral y Escrita', 1, 'ITSE'),
(10, 'Geometria Analitica', 1, 'ITSE'),
(11, 'Simulacion de Sistemas', 1, 'ITSE'),
(12, 'Analisis y Diseño Orientado a ', 2, 'Programacion e Informatica'),
(13, 'Topicos de Manejo Financiero', 2, 'Entorno Social'),
(14, 'Sistemas Digitales y Electroni', 2, 'Arquitectura de Computadoras'),
(15, 'Probabilidad y Estadistica', 2, 'Matematicas'),
(16, 'Metodologia de la Informacion', 2, 'Entorno Social'),
(17, 'Calculo Vectorial', 2, 'ITSE'),
(18, 'Estatica', 2, 'ITSE'),
(19, 'Estructuras de Datos', 2, 'ITSE'),
(20, 'Etica Profesional', 2, 'ITSE'),
(21, 'Sistemas Operativos', 2, 'ITSE'),
(22, 'Transformadas Especiales', 2, 'ITSE'),
(23, 'Lenguajes de Programacion', 3, 'Programacion e Informatica'),
(24, 'Ingenieria de Software', 3, 'Programacion e Informatica'),
(25, 'Fundamentos de Base de Datos', 3, 'Tratamiento de la Informatica'),
(26, 'Algebra Lineal', 3, 'Matematicas'),
(27, 'Medio Ambiente y Desarrollo Su', 3, 'Entorno Social'),
(28, 'Cinematica y Dinamica', 3, 'ITSE'),
(29, 'Ecuaciones Diferenciales y en ', 3, 'ITSE'),
(30, 'Electricidad y Magnetismo', 3, 'ITSE'),
(31, 'Ingenieria de Software', 3, 'ITSE'),
(32, 'Neumatica e Hidraulica', 3, 'ITSE'),
(33, 'Estructura de Datos', 4, 'Tratamiento de la Informatica'),
(34, 'Fundamentos de Redes', 4, 'Redes'),
(35, 'Analisis y Diseño de Software', 4, 'Tratamiento de la Informatica'),
(36, 'Matematicas Aplicadas', 4, 'Matematicas'),
(37, 'Manejadores y Lenguajes de Con', 4, 'Tratamiento de la Informatica'),
(38, 'Fundamentos de Termodinamica', 4, 'ITSE'),
(39, 'Optica y Acustica', 4, 'ITSE'),
(40, 'Comercializacion en Tecnologia', 4, 'ITSE'),
(41, 'Aspectos Básicos en el Desarro', 4, 'ITSE'),
(42, 'Circuitos Electricos', 4, 'ITSE'),
(43, 'Principios de Diseño de Interf', 5, 'Interacion Hombre-Maquina'),
(44, 'Redes de Computadoras', 5, 'Redes'),
(45, 'Desarrollo e Implementacion de', 5, 'Tratamiento de la Informatica'),
(46, 'Geometria Analitica y Graficac', 5, 'Matematicas'),
(47, 'Gestion de Unidades Informatic', 5, 'Entorno Social'),
(48, 'Bases de Datos', 5, 'ITSE'),
(49, 'Prababilidad y Estadistica', 5, 'ITSE'),
(50, 'Dispositivos y Circuitos Elect', 5, 'ITSE'),
(51, 'Sistemas Digitales', 5, 'ITSE'),
(52, 'Teoria Electromagnetica', 5, 'ITSE'),
(53, 'Programacion de Servidores Web', 6, 'Programacion e Informatica'),
(54, 'Administracion de Redes', 6, 'Redes'),
(55, 'Sistemas de Informacion', 6, 'Tratamiento de la Informatica'),
(56, 'Seminario de Creatividad e Inn', 6, 'Entorno Social'),
(57, 'Redaccion de Textos en ingles', 6, 'Entorno Social'),
(58, 'Ingenieria de Control', 6, 'ITSE'),
(59, 'Maquinas Electricas', 6, 'ITSE'),
(60, 'Amplificacion de Señales', 6, 'ITSE'),
(61, 'Sistemas Analogicos', 6, 'ITSE'),
(62, 'Fundamentos de Sistemas de Com', 6, 'ITSE'),
(63, 'Programacion de Servidores Web', 7, 'Programacion e Informatica'),
(64, 'Infraestructura Informatica', 7, 'Software Base'),
(65, 'Innovacion Tecnologica', 7, 'Programacion e Informatica'),
(66, 'Optativa I', 7, 'Optativa'),
(67, 'Administracion de Proyectos de', 7, 'Entorno Social'),
(68, 'Sistemas de Datos Muestreados', 7, 'ITSE'),
(69, 'Microprocesadores', 7, 'ITSE'),
(70, 'Comunicaciones Digitales', 7, 'ITSE'),
(71, 'Electronica Analogica', 7, 'ITSE'),
(72, 'Telefonia Digital', 7, 'ITSE'),
(73, 'Inteligencia Artificial', 8, 'Interacion Hombre-Maquina'),
(74, 'Sistemas Operativos', 8, 'Software Base'),
(75, 'Modelos de Calidad de Software', 8, 'Programacion e Informatica'),
(76, 'Optativa II Temas Selectos', 8, 'Optativa'),
(77, 'Optativa II Seguridad de softw', 8, 'Optativa'),
(78, 'Manejo Economico', 8, 'Entorno Social'),
(79, 'Sistemas de Audio y Video', 8, 'ITSE'),
(80, 'Dispositivos Logicos Programab', 8, 'ITSE'),
(81, 'Microcontroladores', 8, 'ITSE'),
(82, 'Control Digital', 8, 'ITSE'),
(83, 'Transmision de Datos', 8, 'ITSE'),
(84, 'Emprendedores', 9, 'Entorno Social'),
(85, 'Sistemas Distribuidos', 9, 'Software Base'),
(86, 'Optativa III', 9, 'Optativa'),
(87, 'Optativa IV', 9, 'Optativa'),
(88, 'Etica y Normativa Juridica', 9, 'Entorno Social'),
(89, 'Asignatura obligatoria de elec', 9, 'ITSE'),
(90, 'Asignaturas optativas', 9, 'ITSE');


